Add files via upload
Andr0901/hash-map pull request #1
Opened 2020-03-09 10:52 UTC by Andr0901

30969717

2020-03-15 22:16 UTC, glebshp requested changes
В некоторые детали не вникал, сначала надо исправить имеющиеся замечания

2020-03-15 22:16 UTC, glebshp commented on hash_map.h
> +    public:
public и private на одном отступе с методами и полями плохо читается

2020-03-15 22:16 UTC, glebshp commented on hash_map.h
> +    typename std::list<std::pair <const KeyType, ValueType>>::iterator;
Здесь тоже нужен какой-то отступ, чтобы было визуально понятно, что это продолжение предыдущей строки

2020-03-15 22:16 UTC, glebshp commented on hash_map.h
> +    const size_t TABLE_SIZE = 8e5;
очень много, надо начинать с маленького размера таблицы и масштабировать его по мере увеличения

2020-03-15 22:16 UTC, glebshp commented on hash_map.h
> +    template<typename It>
It - избыточная экономия, сделай, пожалуйста, более длинное название

2020-03-15 22:16 UTC, glebshp commented on hash_map.h
> +            if (i -> first == a.first)
Оператор -> не принято отбивать пробелами

2020-03-15 22:16 UTC, glebshp commented on hash_map.h
> +        for (const auto& i : table_[h])
Переменную i используют для индекса, для range based for она не подходит

2020-03-15 22:16 UTC, glebshp commented on hash_map.h
> +        for (auto& i : table_[h])
В промышленном программировании принято всегда использовать скобки для for и if, даже если там всего одна строка. Единственное исключение - если действие находится с if или for непосредственно в одной строке, но мне так не нравится

2020-05-31 00:21 UTC, glebshp requested changes

2020-05-31 00:21 UTC, glebshp commented on hash_map.h
> +// Hashtable with separate chaining
Хочу чтобы описание класса содержало.

1. Что делает класс.
2. Какая реализация таблицы используется.
3. Какая стратегия масштабирования используется.
4. За счёт чего гарантируется линейное итерирование.

2020-05-31 00:21 UTC, glebshp commented on hash_map.h
> +    size_t nElements_, table_size_;
1. Не следует объявлять два поля в одной строке.
2. Блок приватных полей сильно менее интересен читателю, чем блок публичных методов, поэтому должен идти в конце.

2020-05-31 00:21 UTC, glebshp commented on hash_map.h
> +        if (nElements_ != table_size_) {
А почему тут !=, а не < ?

2020-05-31 00:21 UTC, glebshp commented on hash_map.h
> +        table_[h].push_back(--elements_.end());
.back() ?

2020-05-31 00:21 UTC, glebshp commented on hash_map.h
> +    void expand() {
То что делает метод не соответствует его названию. Метод expand должен расширять, а этот проверяет некоторое условие и расширяет только если оно выполняется. Можно назвать expand_if_necessary

2020-05-31 00:21 UTC, glebshp commented on hash_map.h
> +    ValueType& operator[](const KeyType& i) {
Мне тут не нравится, что мы вызываем find два раза. Можно сделать внутреннюю версию insert, которая будет возвращать итератор на вставленный элемент

2020-06-13 22:07 UTC, Andr0901 commented on hash_map.h
> +        table_[h].push_back(--elements_.end());
Как тут использовать back(), если он возвращает элемент, а тут нужен итератор?

2020-06-19 23:02 UTC, glebshp requested changes

2020-06-19 23:02 UTC, glebshp commented on hash_map.h
> +        if (iter == end()) {
Всё равно получилось, что ты два раза вычисляешь хеш, сначала в find, потому в returning_insert, а можно один

2020-06-19 23:02 UTC, glebshp commented on hash_map.h
> +        table_size_ = 1;
А почему мы не делаем тут resize для table_? Казалось бы, либо resize, либо не менять table_size_

2020-06-19 23:02 UTC, glebshp commented on hash_map.h
> +            table_[hasher_(elements_.back().first) % table_size_].clear();
Зачем тут тратить время на дорогие вычисления хеша, почему бы просто не освободить всё циклом?

2020-06-19 23:02 UTC, glebshp commented on hash_map.h
> +            table_[hasher_(elements_.back().first) % table_size_].clear();
При условии, что мы потом уменьшаем таблицу, если нет, то так правильнее

2020-06-21 00:24 UTC, glebshp approved these changes

2020-06-21 08:19 UTC, merged